import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';

export const generateMeasurementsPDF = async (tableData, user) => {
  try {
    // Extract all unique measurement keys from the data
    const measurementKeys = new Set();
    tableData.forEach(row => {
      Object.keys(row).forEach(key => {
        if (key !== 'name' && key !== 'type') {
          measurementKeys.add(key);
        }
      });
    });
    const measurementColumns = Array.from(measurementKeys);

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Measurement Summary Report</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              margin: 20px;
              color: #333;
            }
            .header {
              text-align: center;
              margin-bottom: 30px;
              border-bottom: 2px solid #7C3AED;
              padding-bottom: 20px;
            }
            .header h1 {
              color: #7C3AED;
              margin: 0;
              font-size: 24px;
            }
            .header p {
              margin: 5px 0;
              color: #666;
            }
            .user-info {
              background: #f8f9fa;
              padding: 15px;
              border-radius: 8px;
              margin-bottom: 20px;
            }
            .user-info h3 {
              margin: 0 0 10px 0;
              color: #7C3AED;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
            }
            th, td {
              border: 1px solid #ddd;
              padding: 12px;
              text-align: left;
            }
            th {
              background-color: #7C3AED;
              color: white;
              font-weight: bold;
            }
            tr:nth-child(even) {
              background-color: #f9f9f9;
            }
            .type-badge {
              padding: 4px 8px;
              border-radius: 12px;
              font-size: 12px;
              font-weight: bold;
            }
            .body-badge {
              background-color: #EDE9FE;
              color: #7C3AED;
            }
            .object-badge {
              background-color: #FEF3C7;
              color: #F59E0B;
            }
            .footer {
              margin-top: 30px;
              text-align: center;
              font-size: 12px;
              color: #666;
              border-top: 1px solid #ddd;
              padding-top: 15px;
            }
            .measurement-cell {
              text-align: center;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Data Capturing App</h1>
            <p>Measurement Summary Report</p>
            <p>Generated on: ${new Date().toLocaleDateString()}</p>
          </div>

          <div class="user-info">
            <h3>User Information</h3>
            <p><strong>Name:</strong> ${user?.fullName || 'N/A'}</p>
            <p><strong>Email:</strong> ${user?.email || 'N/A'}</p>
            <p><strong>Report Date:</strong> ${new Date().toLocaleDateString()}</p>
          </div>

          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Type</th>
                ${measurementColumns.map(key => `<th>${key.charAt(0).toUpperCase() + key.slice(1)}</th>`).join('')}
              </tr>
            </thead>
            <tbody>
              ${tableData.map(row => `
                <tr>
                  <td>${row.name}</td>
                  <td>
                    <span class="type-badge ${row.type === 'Body' ? 'body-badge' : 'object-badge'}">
                      ${row.type}
                    </span>
                  </td>
                  ${measurementColumns.map(key => `<td class="measurement-cell">${row[key] || 'N/A'}</td>`).join('')}
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="footer">
            <p>This report was generated by Data Capturing App</p>
            <p>© ${new Date().getFullYear()} Data Capturing App. All rights reserved.</p>
          </div>
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({
      html: htmlContent,
      base64: false
    });

    return uri;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
};

export const viewPDF = async (pdfUri) => {
  try {
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(pdfUri, {
        mimeType: 'application/pdf',
        dialogTitle: 'View Measurement Report'
      });
    } else {
      throw new Error('Sharing is not available on this device');
    }
  } catch (error) {
    console.error('Error viewing PDF:', error);
    throw error;
  }
};